-- Abuse-Schutz für Sharing (report-getrieben, auditierbar, ohne Moralfilter).
-- Einmalig im Supabase SQL-Editor ausführen (Dashboard -> SQL Editor -> New query).
-- VORAUSSETZUNG: sharing.sql und profiles.sql wurden bereits ausgeführt.

create table if not exists public.moderation_reports (
  id bigint generated by default as identity primary key,
  reporter_user_id uuid not null references auth.users (id) on delete cascade,
  resource_type text not null check (resource_type in ('tab', 'section', 'link', 'share_token')),
  resource_id text not null,
  reason_code text not null check (
    reason_code in (
      'csam',
      'animal_abuse',
      'non_consensual_intimate',
      'human_trafficking',
      'malware_phishing',
      'scam',
      'terror_extremism_illegal',
      'threats_doxxing',
      'serious_crime_market_or_instruction',
      'other_illegal'
    )
  ),
  details text,
  reported_domain text,
  reported_url text,
  status text not null default 'open' check (status in ('open', 'in_review', 'actioned', 'dismissed')),
  reviewed_by_admin_id uuid references auth.users (id) on delete set null,
  reviewed_at timestamptz,
  action_note text,
  created_at timestamptz not null default now()
);

create index if not exists moderation_reports_status_created_idx
  on public.moderation_reports (status, created_at desc);

create index if not exists moderation_reports_resource_created_idx
  on public.moderation_reports (resource_type, resource_id, created_at desc);

create index if not exists moderation_reports_reporter_created_idx
  on public.moderation_reports (reporter_user_id, created_at desc);

create table if not exists public.moderation_events (
  id bigint generated by default as identity primary key,
  event_type text not null check (
    event_type in (
      'share_revoked',
      'user_sharing_disabled',
      'user_suspended',
      'domain_blocked',
      'report_dismissed',
      'content_reinstated'
    )
  ),
  actor_admin_id uuid references auth.users (id) on delete set null,
  target_user_id uuid references auth.users (id) on delete set null,
  report_id bigint references public.moderation_reports (id) on delete set null,
  share_token text references public.share_tokens (token) on delete set null,
  domain_pattern text,
  block_scope text check (block_scope in ('share_only', 'all')),
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists moderation_events_created_idx
  on public.moderation_events (created_at desc);

create index if not exists moderation_events_report_idx
  on public.moderation_events (report_id, created_at desc);

create table if not exists public.blocked_domains (
  id bigint generated by default as identity primary key,
  domain_pattern text not null unique check (length(trim(domain_pattern)) > 0),
  block_scope text not null check (block_scope in ('share_only', 'all')),
  reason text,
  blocked_by_admin_id uuid references auth.users (id) on delete set null,
  lifted_at timestamptz,
  lifted_by_admin_id uuid references auth.users (id) on delete set null,
  created_at timestamptz not null default now()
);

create index if not exists blocked_domains_active_scope_idx
  on public.blocked_domains (block_scope, created_at desc)
  where lifted_at is null;

create index if not exists blocked_domains_active_pattern_idx
  on public.blocked_domains (domain_pattern)
  where lifted_at is null;

alter table public.moderation_reports enable row level security;
alter table public.moderation_events enable row level security;
alter table public.blocked_domains enable row level security;
